baseurl = "https://quizzical-colden-919fbe.netlify.com/"
title = "Outreach Shame"
theme = "nederburg"
languageCode = "en-us"

disqusShortname = ""
googleAnalytics = ""

preserveTaxonomyNames = true
paginate = 5 #frontpage pagination

[params]
  slogan = "A carefully curated list of ways how not to outreach"
  description = "A carefully curated list of ways how not to outreach" # meta description
  author = "Snipcart"
  authorLink = "https://snipcart.com"
  bio = [
    ""
  ]
  copyright = [
    "&copy; 2018 Outreach Shame",
    "Nederburg Hugo Theme by [Appernetic](https://appernetic.io).",
    "A port of Tracks by Compete Themes."
  ]


  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below (it is also used in Gravatar for the bio).
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "geeks@snipcart.com"

  # Nav links in the side bar
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "About"
  url = "about/"
  weight = 2

  [[menu.main]]
  name = "Get in touch"
  url = "contact/"
  weight = 3

  [params.social]
  facebook      = "full profile url in facebook"
  googleplus    = "full profile url in googleplus"
  email         = "email@example.com"
  twitter       = "full profile url in twitter"
  linkedin      = "full profile url in linkedin"
  stackoverflow = "full profile url in stackoverflow"
  instagram     = "full profile url in instagram"
  github        = "full profile url in github"
  pinterest     = "full profile url in pinterest"
  rss           = true